[pyprland]
plugins = [
"scratchpads",
"lost_windows",
]

[scratchpads.term]
animation = "fromRight"
command = "alacritty --class dropterm"
class = "dropterm"
size = "50% 95%"
max_size = "1920px 100%"
